import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "../redux/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quantum Possibilities",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="QP_colors">
      <body className={inter.className}>
        <ReduxProvider> {children}</ReduxProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
